services:
  postgres:
    image: postgres:latest
    container_name: flow-meter-psql
    environment:
      POSTGRES_USER: serveruser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: flow-meter
    ports:
      - "5002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U serveruser -d flow-meter"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
    driver: local