server:
  port: 8080

app:
  base-url: http://localhost:${server.port}

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5002/flow-meter
    username: serveruser
    password: password123
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret: # todo: it a danger to store secret here
  jpa:
    show-sql: false
    open-in-view: true  # TODO: to disable

#logging:
#  level:
#    org:
#      springframework:
#      security=TRACE:

springdoc:
  swagger-ui:
    enabled: true
