server:
  port: ${SERVER_PORT:8080}

app:
  base-url: ${BASE_URL:http://localhost}:${server.port}

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_URL}/${DB_NAME:flow-meter}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
  mail:
    host: smtp.gmail.com      # todo: hardcode??
    port: 587                 # todo: hardcode??
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: false
    open-in-view: false  # TODO: to disable


#logging:
#  level:
#    org:
#      springframework:
#      security=TRACE:

springdoc:
  swagger-ui:
    enabled: true
