INSERT INTO flow (account_id, title, description, target_percentage, created_at, updated_at, deleted)
VALUES
    (1, 'SQL Fundamentals', 'SQL Fundamental, HTTP/HTTPS, conspecting', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, 'Driving', 'Everyday learn road rules', 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, 'Gym', 'Do gym, improve physic', 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, 'Web Development', 'Learn HTML, CSS, JS', 85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, 'Cooking', 'Master Italian cuisine', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, 'Photography', 'Learn to shoot landscapes', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, 'Data Science', 'Python, pandas, ML basics', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, 'Running', 'Prepare for a marathon', 65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, 'Guitar', 'Learn chords and solos', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, 'Project Management', 'Study Scrum and Kanban', 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false);

INSERT INTO step (flow_id, day, created_at, updated_at, deleted)
VALUES
    -- Flow 1: SQL Fundamentals (10 steps)
    (1, '2025-01-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-01-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-02-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-03-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-03-21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-03-22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-04-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-05-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, '2025-06-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 2: Driving (12 steps)
    (2, '2025-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-02-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-02-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-03-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-03-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-03-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-04-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-05-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-06-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-07-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-08-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, '2025-09-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 3: Gym (8 steps)
    (3, '2025-03-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, '2025-03-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, '2025-03-24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, '2025-03-28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, '2025-04-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, '2025-05-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, '2025-06-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, '2025-07-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 4: Web Development (15 steps)
    (4, '2025-01-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-01-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-02-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-02-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-03-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-03-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-04-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-04-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-05-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-05-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-06-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-06-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-07-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-07-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, '2025-08-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 5: Cooking (6 steps)
    (5, '2025-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, '2025-03-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, '2025-04-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, '2025-05-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, '2025-06-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, '2025-07-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 6: Photography (7 steps)
    (6, '2025-03-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, '2025-04-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, '2025-05-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, '2025-06-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, '2025-07-30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, '2025-08-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, '2025-09-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 7: Data Science (10 steps)
    (7, '2025-01-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-02-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-03-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-04-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-05-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-06-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-07-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-08-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-09-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, '2025-10-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 8: Running (9 steps)
    (8, '2025-03-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-03-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-04-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-05-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-06-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-07-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-08-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-09-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, '2025-10-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 9: Guitar (8 steps)
    (9, '2025-02-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, '2025-03-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, '2025-04-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, '2025-05-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, '2025-06-30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, '2025-08-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, '2025-09-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, '2025-10-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 10: Project Management (7 steps)
    (10, '2025-01-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, '2025-02-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, '2025-03-30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, '2025-05-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, '2025-06-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, '2025-07-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, '2025-08-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false);

INSERT INTO cases (step_id, text, percent, counting, created_at, updated_at, deleted)
VALUES
    -- Flow 1: SQL Fundamentals (Steps 1-10)
    (1, 'Study SQL SELECT basics', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, 'Write 5 simple queries', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, 'Read about JOIN types', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (1, 'Test INNER JOIN', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, 'Learn WHERE clause', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, 'Filter with conditions', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, 'Practice LIKE operator', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (2, 'Use AND/OR operators', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, 'Study GROUP BY', 90, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, 'Aggregate with COUNT', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, 'Use HAVING clause', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (3, 'Test on sample data', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, 'Learn subqueries', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, 'Write nested SELECT', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, 'Optimize subquery', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (4, 'Test correlated subquery', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, 'Study indexes', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, 'Create a B-tree index', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, 'Measure query speed', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (5, 'Drop unused index', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, 'Learn transactions', 90, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, 'Test COMMIT', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, 'Test ROLLBACK', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (6, 'Use in flowMeter', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, 'Study triggers', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, 'Write AFTER INSERT trigger', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, 'Test trigger logic', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (7, 'Debug trigger', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, 'Learn stored procedures', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, 'Create a procedure', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, 'Call procedure in DB', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (8, 'Optimize procedure', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, 'Study views', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, 'Create a simple view', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, 'Test view with JOIN', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (9, 'Update view logic', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, 'Learn normalization', 90, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, 'Apply 1NF to DB', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, 'Apply 2NF to DB', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (10, 'Test relations', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 2: Driving (Steps 11-22)
    (11, 'Drive 30 min in city', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (11, 'Practice parallel parking', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (11, 'Learn 5 road signs', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (11, 'Test turn signals', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (12, 'Drive on highway', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (12, 'Practice lane change', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (12, 'Night driving basics', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (12, 'Adjust headlights', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (13, 'Advanced parallel parking', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (13, 'Reverse driving practice', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (13, 'Emergency braking', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (13, 'Mirror adjustment', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (14, 'Drive in traffic', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (14, 'Lane changing practice', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (14, 'Yield to pedestrians', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (14, 'Test horn usage', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (15, 'Roundabout practice', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (15, 'City navigation', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (15, 'Fuel station stop', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (15, 'Check tire pressure', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (16, 'Long trip 1 hour', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (16, 'Highway rules review', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (16, 'Overtake safely', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (16, 'Rest stop practice', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (17, 'Rain driving practice', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (17, 'Fog driving basics', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (17, 'Wiper usage test', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (17, 'Slow speed control', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (18, 'Mountain driving', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (18, 'Steep incline practice', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (18, 'Downhill braking', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (18, 'Gear shifting', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (19, 'Drive with instructor', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (19, 'Mock driving test', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (19, 'Fix turning mistakes', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (19, 'Practice signals', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (20, 'Final driving test prep', 90, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (20, 'Simulate test route', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (20, 'Review weak points', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (20, 'Celebrate passing', 100, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (21, 'Drive in rush hour', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (21, 'Practice merging', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (21, 'Test parking in lot', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (21, 'Learn traffic rules', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (22, 'Cross-country trip', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (22, 'Navigate small towns', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (22, 'Test long-distance focus', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (22, 'Check car maintenance', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 3: Gym (Steps 23-30)
    (23, 'Bench press 50kg', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (23, 'Push-ups 20 reps', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (23, 'Stretch chest', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (23, 'Warm-up 10 min', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (24, 'Squats 15 reps', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (24, 'Leg press 60kg', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (24, 'Lunges 10 per leg', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (24, 'Cool down stretch', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (25, 'Deadlift 70kg', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (25, 'Pull-ups 8 reps', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (25, 'Back stretch', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (25, 'Core planks 1 min', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (26, 'Bicep curls 12kg', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (26, 'Tricep dips 15 reps', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (26, 'Arm stretch', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (26, 'Shoulder press 10kg', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (27, 'Cardio 20 min', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (27, 'Treadmill 5km', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (27, 'Jump rope 100 reps', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (27, 'Cool down jog', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (28, 'Leg curls 50kg', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (28, 'Calf raises 20 reps', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (28, 'Leg stretch', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (28, 'Balance exercise', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (29, 'Chest fly 15kg', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (29, 'Push-ups wide grip', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (29, 'Stretch upper body', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (29, 'Warm-up cardio', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (30, 'Pull-ups 10 reps', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (30, 'Rows 60kg', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (30, 'Core twists 50 reps', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (30, 'Back extension', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 4: Web Development (Steps 31-45)
    (31, 'Learn HTML tags', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (31, 'Create a simple page', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (31, 'Add headings', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (31, 'Test in browser', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (32, 'Study CSS basics', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (32, 'Style a div', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (32, 'Use colors', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (32, 'Test responsiveness', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (33, 'Learn flexbox', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (33, 'Create a layout', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (33, 'Center elements', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (33, 'Test on mobile', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (34, 'Study JS variables', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (34, 'Write a function', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (34, 'Log to console', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (34, 'Debug JS code', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (35, 'Learn DOM manipulation', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (35, 'Change text on click', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (35, 'Add event listener', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (35, 'Test button', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (36, 'Study arrays', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (36, 'Loop through array', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (36, 'Filter array', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (36, 'Map array', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (37, 'Learn promises', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (37, 'Fetch API call', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (37, 'Handle errors', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (37, 'Test async code', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (38, 'Study CSS grid', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (38, 'Create a grid layout', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (38, 'Adjust columns', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (38, 'Test grid on tablet', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (39, 'Learn ES6 syntax', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (39, 'Use arrow functions', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (39, 'Destructure objects', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (39, 'Test in console', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (40, 'Study React basics', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (40, 'Create a component', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (40, 'Add props', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (40, 'Test rendering', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (41, 'Learn React state', 90, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (41, 'Update state on click', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (41, 'Use useEffect', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (41, 'Test side effects', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (42, 'Study routing', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (42, 'Add React Router', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (42, 'Create 3 routes', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (42, 'Test navigation', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (43, 'Learn API integration', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (43, 'Fetch data from API', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (43, 'Display API data', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (43, 'Handle loading state', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (44, 'Study CSS animations', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (44, 'Add fade effect', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (44, 'Test keyframes', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (44, 'Optimize animation', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (45, 'Build a small project', 90, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (45, 'Deploy to GitHub Pages', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (45, 'Test live site', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (45, 'Fix bugs', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 5: Cooking (Steps 46-51)
    (46, 'Cook pasta', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (46, 'Make tomato sauce', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (46, 'Grate cheese', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (46, 'Plate dish', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (47, 'Bake bread', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (47, 'Knead dough', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (47, 'Proof dough', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (47, 'Test oven temp', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (48, 'Cook risotto', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (48, 'Stir broth slowly', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (48, 'Add parmesan', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (48, 'Taste test', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (49, 'Grill chicken', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (49, 'Marinate meat', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (49, 'Check grill heat', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (49, 'Serve with sauce', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (50, 'Bake a cake', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (50, 'Mix batter', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (50, 'Frost cake', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (50, 'Decorate top', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (51, 'Cook pizza', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (51, 'Roll dough', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (51, 'Add toppings', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (51, 'Bake at 200C', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 6: Photography (Steps 52-58)
    (52, 'Set up camera', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (52, 'Adjust aperture', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (52, 'Take 5 shots', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (52, 'Check focus', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (53, 'Learn shutter speed', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (53, 'Test motion blur', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (53, 'Shoot moving object', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (53, 'Review shots', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (54, 'Study ISO settings', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (54, 'Test in low light', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (54, 'Adjust noise', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (54, 'Save best shot', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (55, 'Learn composition', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (55, 'Use rule of thirds', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (55, 'Frame a landscape', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (55, 'Test angles', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (56, 'Edit in Lightroom', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (56, 'Adjust exposure', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (56, 'Crop image', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (56, 'Export photo', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (57, 'Shoot portraits', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (57, 'Use soft lighting', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (57, 'Pose subject', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (57, 'Edit skin tones', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (58, 'Night photography', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (58, 'Use tripod', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (58, 'Long exposure test', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (58, 'Capture stars', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 7: Data Science (Steps 59-68)
    (59, 'Install Python', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (59, 'Set up Jupyter', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (59, 'Run hello world', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (59, 'Test libraries', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (60, 'Learn pandas basics', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (60, 'Load CSV data', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (60, 'Filter rows', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (60, 'Group data', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (61, 'Study NumPy', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (61, 'Create arrays', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (61, 'Test operations', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (61, 'Optimize memory', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (62, 'Learn matplotlib', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (62, 'Plot a line chart', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (62, 'Add labels', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (62, 'Save plot', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (63, 'Study scikit-learn', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (63, 'Train a model', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (63, 'Test accuracy', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (63, 'Tune parameters', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (64, 'Clean dataset', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (64, 'Handle missing data', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (64, 'Remove outliers', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (64, 'Test cleaned data', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (65, 'Learn regression', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (65, 'Fit linear model', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (65, 'Predict values', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (65, 'Evaluate R2', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (66, 'Study classification', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (66, 'Train logistic model', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (66, 'Test precision', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (66, 'Plot ROC curve', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (67, 'Learn clustering', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (67, 'Run k-means', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (67, 'Visualize clusters', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (67, 'Test silhouette score', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (68, 'Build a project', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (68, 'Analyze real data', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (68, 'Present results', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (68, 'Document code', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 8: Running (Steps 69-77)
    (69, 'Run 3km', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (69, 'Warm-up 5 min', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (69, 'Stretch legs', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (69, 'Track pace', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (70, 'Run 5km', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (70, 'Practice breathing', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (70, 'Hydrate properly', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (70, 'Cool down jog', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (71, 'Hill sprints', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (71, 'Run uphill 5 times', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (71, 'Test endurance', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (71, 'Stretch calves', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (72, 'Run 8km', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (72, 'Monitor heart rate', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (72, 'Adjust speed', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (72, 'Post-run stretch', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (73, 'Interval training', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (73, 'Sprint 1 min x 5', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (73, 'Rest between sets', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (73, 'Track intervals', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (74, 'Run 10km', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (74, 'Test stamina', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (74, 'Hydrate mid-run', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (74, 'Cool down walk', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (75, 'Trail running', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (75, 'Navigate uneven terrain', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (75, 'Test trail shoes', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (75, 'Stretch after trail', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (76, 'Run 15km', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (76, 'Plan long route', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (76, 'Track distance', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (76, 'Recover with stretch', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (77, 'Marathon prep run', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (77, 'Run 20km', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (77, 'Simulate race day', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (77, 'Rest and hydrate', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 9: Guitar (Steps 78-85)
    (78, 'Learn C chord', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (78, 'Practice strumming', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (78, 'Tune guitar', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (78, 'Play 5 min', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (79, 'Learn G chord', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (79, 'Switch C to G', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (79, 'Play a simple song', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (79, 'Adjust finger position', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (80, 'Learn D chord', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (80, 'Practice chord changes', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (80, 'Strum pattern practice', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (80, 'Record progress', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (81, 'Learn A minor', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (81, 'Play Am to G', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (81, 'Test rhythm', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (81, 'Fix finger pain', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (82, 'Learn E major', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (82, 'Switch E to A', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (82, 'Play a full song', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (82, 'Practice 10 min', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (83, 'Study barre chords', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (83, 'Play F chord', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (83, 'Strengthen fingers', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (83, 'Test barre transitions', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (84, 'Learn a solo', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (84, 'Practice bends', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (84, 'Test speed', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (84, 'Record solo', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (85, 'Play a complex song', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (85, 'Mix chords and solo', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (85, 'Perform for friends', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (85, 'Fix timing', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),

    -- Flow 10: Project Management (Steps 86-92)
    (86, 'Read Scrum guide', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (86, 'List Scrum roles', 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (86, 'Define sprint', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (86, 'Write backlog', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (87, 'Study Kanban', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (87, 'Create Kanban board', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (87, 'Set WIP limits', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (87, 'Test flow', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (88, 'Learn sprint planning', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (88, 'Plan a mock sprint', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (88, 'Estimate tasks', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (88, 'Review plan', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (89, 'Study daily standup', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (89, 'Simulate standup', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (89, 'Track blockers', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (89, 'Improve format', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (90, 'Learn sprint review', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (90, 'Present mock results', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (90, 'Gather feedback', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (90, 'Adjust backlog', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (91, 'Study retrospective', 85, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (91, 'Run a retro session', 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (91, 'List improvements', 75, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (91, 'Plan next steps', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (92, 'Apply Scrum to project', 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (92, 'Track progress', 65, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (92, 'Deliver increment', 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false),
    (92, 'Review success', 55, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false);
